name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/apps/send-email-consumer

          git pull origin main

          if [[ "$(docker images -q send-email-consumer:latest 2> /dev/null)" == "" ]]; then
            echo "Building the Docker image using Buildx..."
            docker buildx build --platform linux/arm64 -t send-email-consumer:latest --load .
          else
            echo "Docker image already exists, skipping build..."
          fi

          if [[ "$(docker ps -q -f name=send-email-consumer)" ]]; then
            echo "Stopping and removing existing container..."
            docker stop send-email-consumer
            docker rm send-email-consumer
          fi

          docker run -d --name send-email-consumer --restart unless-stopped \
            -e RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
            -e KAFKA_BROKER=${{ secrets.KAFKA_BROKER }} \
            -e KAFKA_TOPIC=${{ secrets.KAFKA_TOPIC }} \
            -e KAFKA_GROUP_ID=${{ secrets.KAFKA_GROUP_ID }} \
            send-email-consumer:latest

          docker image prune -f
          docker rmi $(docker images --filter "dangling=true" -q) || true
