name: Deploy to VM

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker stop send-email-consumer || true
          docker rm send-email-consumer || true
          cd /home/ubuntu/apps/send-email-consumer
          git pull origin main
          docker build -t send-email-consumer:latest .
          docker run -d --name send-email-consumer --restart unless-stopped \
            -e RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
            -e KAFKA_BROKER=${{ secrets.KAFKA_BROKER }} \
            -e KAFKA_TOPIC=${{ secrets.KAFKA_TOPIC }} \
            -e KAFKA_GROUP_ID=${{ secrets.KAFKA_GROUP_ID }} \
            send-email-consumer:latest
          docker image prune -f
          docker rmi $(docker images --filter "dangling=true" -q) || true
